'use strict'

export const APP_INIT = 'APP_INIT'
export const FETCH_PRICE = 'FETCH_PRICE'
export const FETCH_PRICE_REQUEST = 'FETCH_PRICE_REQUEST'
export const FETCH_PRICE_SUCCESS = 'FETCH_PRICE_SUCCESS'
export const FETCH_PRICE_FAILURE = 'FETCH_PRICE_FAILURE'
